name: Xcode - Build and Analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest"
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Build archive
        run: xcodebuild -scheme "Project SITNU" -target "Project SITNU" -configuration Release clean archive -archivePath "build/sitnu.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcbeautify
      - name: Export ipa
        run: mv build/sitnu.xcarchive/Products/Applications/ build/sitnu.xcarchive/Products/Payload && cd build/sitnu.xcarchive/Products && zip -r sitnu.ipa Payload/
      - name: Upload ipa
        uses: actions/upload-artifact@v3
        with:
          name: unsigned-ipa
          path: build/sitnu.xcarchive/Products/sitnu.ipa
            
            
            
